# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: mongo-dev
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongo-compose-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /mnt/c/works/study/React-jsonschema-form/mongodb/configdb:/data/configdb
      - /mnt/c/works/study/React-jsonschema-form/mongodb/initdb:/docker-entrypoint-initdb.d
      - mongoDataStore:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - mongo-compose-network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

networks:
  mongo-compose-network:
    driver: bridge
volumes:
  mongoDataStore:
    driver: local
